export const skills = {
  eyebrow: "Skills",
  title: "Tools and technologies I have used across recent projects.",
  tags: [
    "JavaScript",
    "HTML",
    "CSS",
    "WebGL",
    "Three.js",
    "GLSL",
    "React",
    "Node.js",
    "Express",
    "Handlebars",
    "Web Audio API",
    "Tone.js",
    "Python",
    "Flask",
    "SQL",
    "MySQL",
    "Database Design",
    "CRUD",
    "Collaboration",
    "Git/GitHub",
  ],
};
